import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router';
import Link from 'next/link';
import Nav from '@/components/nav';



const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image className={styles.logo} onClick={() => router.push('/')} src='/logo.png' width='200' height='100'/>
        <Nav/>
        <div className={styles.topcont}> 
        <div className={styles.titlecont}> 
 <div className={styles.title}>
 I’m a passionate UX/UI designer from Vancouver, BC. 
 I'm currently nearing the end of my studies in the Digital Design and Development program at BCIT. 
I'm about to begin my practicum at Honeygold Cases as a UX/UI Designer and Graphic Designer.
 </div>
 <div className={styles.title}>
I have always been drawn to things that are aesthetic 
and the significance it has on influencing one’s impression. I love the process of developing  aesthetic designs, 
and I strive to create meaningful experiences and hopefully inspire those who interact with the work I have produced.
</div>
  
        </div>


         
        <Image className={styles.headshot} src='/headshot.png' width='180' height='180'/>
        
        </div>
        
        <Image className={styles.rotate} src='/Group.png' width='120' height='120'/>

        <div className={styles.connect}> Expertise </div>

        <div className={styles.line2}></div>
        <div className={styles.smalltitle1}> Mobile Design</div>
        <div className={styles.line2}></div>
        <div className={styles.smalltitle1}> User Experience Design</div>
        <div className={styles.line2}></div>
        <div className={styles.smalltitle1}> User Interface Design</div>
        <div className={styles.line2}></div>
        <div className={styles.smalltitle1}> Product Design</div>
        <div className={styles.line2}></div>
        <div className={styles.smalltitle1}> Figma</div>
        <div className={styles.line2}></div>
        <div className={styles.smalltitle1}> Wireframes / Prototyping</div>
        <div className={styles.line2}></div>
        <div className={styles.smalltitle1}> Photoshop / Illustrator / InDesign / After Effect / Premier Pro </div>
        <div className={styles.line2}></div>
        <div className={styles.smalltitle1}> React.js / Next.js</div>
        <div className={styles.line2}></div>
        <div className={styles.smalltitle1}> HTML / CSS / JavaScript</div>
        <div className={styles.line2}></div>
        <div className={styles.smalltitle1}> Front-End Development</div>

        <div className={styles.connect}> Experience </div>
        <div className={styles.line2}></div>
        <div className={styles.smalltitle1}> Honeygold Cases - UX/UI Designer</div>
        <div className={styles.smalltitle}> April 3rd 2023 - Present</div>
        <div className={styles.line2}></div>
        <div className={styles.smalltitle1}> Ohana - Project Manager and Lead UX/UI Designer</div>
        <div className={styles.smalltitle}> September 1st 2022 - December 7th 2022</div>
        <div className={styles.line2}></div>
        <div className={styles.smalltitle1}> LocalScoop - UX/UI Designer</div>
        <div className={styles.smalltitle}> January 1st 2022 - March 1st 2022</div>



      

      <div className={styles.connect}> Let's connect</div>
      <div className={styles.connectdesc}> currently seeking an opportunity in Digital Design, UX/UI Design, and Graphic Design</div>
      
      <div className={styles.socialcont}> 
        <div className={styles.line1}></div>
        <div className={styles.socialcont1}> 

<Link  className={styles.social} href="mailto:sndagneau@gmail.com"> Email </Link>
      <Image className={styles.arrow1} src='/arrow-right.svg' width='50' height='50'/>
        </div>
 <div className={styles.line1}></div>
        <div className={styles.socialcont1}> 
        

 <Link className={styles.social} href='https://www.linkedin.com/in/soleildagneau' target="_blank" rel="noopener noreferrer"> LinkedIn </Link>
      <Image className={styles.arrow1} src='/arrow-right.svg' width='50' height='50'/>
        </div>
 <div className={styles.line1}></div>
        <div className={styles.socialcont1}> 
<Link className={styles.social} href='https://www.instagram.com/notsoleil/' target="_blank" rel="noopener noreferrer"> Instagram </Link>
      <Image className={styles.arrow1} src='/arrow-right.svg' width='50' height='50'/>
        </div>
      
     
     
     
      
      </div>

   
      
      </main>
    </>
  )
}
