import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Nav from '@/components/nav'
import { useRouter } from 'next/router';


export default function Home() {
    const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image className={styles.logo} onClick={() => router.push('/')} src='/logo.png' width='200' height='100'/>
        <Nav/>

        <div className={styles.titlecont1}>
            <div className={styles.projecttitle}> Beach House Brewing Craft Beer Cans</div>
        <div className={styles.projectlongdesc}> Beer can designs of 3 different flavour product types. </div>
       
        </div>
         <div className={styles.line}></div>
            <div className={styles.infocont}>
            <div className={styles.itemcont}> 
                    <div> Year </div>  <div className={styles.info1}> 2022 </div>
                </div>
                
                <div className={styles.itemcont}> 
                    <div> Tools </div>  <div className={styles.info}> Photoshop, Illustrator </div>
                </div>
                <div className={styles.itemcont}> 
                    <div> Project Types </div>  <div className={styles.info}> Product Design, Package Design, Logo Design</div>
                </div>
                <div className={styles.itemcont}> 
                    <div> Roles </div>  <div className={styles.info}> Graphic Designer </div>
                </div>
            </div>
        <Image className={styles.mainpicture} src='/canmock.png' width='800' height='500'/>
        <div className={styles.num}>01</div>
        <div className={styles.title3}> Overview</div>
        
        <div className={styles.desc1}> 
        The task was to create unique packaging and design for three cans or bottles. 
        The packaging across all three designs must be cohesive enough so that it is clear 
        they are from the same brand, but differentiated from each other to represent different flavours. 
        I created these three designs by creating the graphics in Illustrator, distorting the graphics in both Photoshop and Illustrator,
         and creating a mockup of the designs in Photoshop.
         </div>

        
        <div className={styles.num3}>02</div>  
        <div className={styles.title4}> The Inspiration </div>

     
      
        <div className={styles.desc1}> 
        These cans were inspired by one of my favourite bands Beach House. A lot of their album cover artworks
        and the aesthetic of their shows include designs to portray a psychedelic, dark, dystopian feeling. 
        The colour palette and repeating elements such as the distortian and darkness, create a cohesive packaging line.
        </div>



          
        <div className={styles.num3}>03</div>  
        <div className={styles.title4}> Client Proofs</div>
        <div className={styles.proofimgcont}>
             <Image className={styles.proofimg} src='/clientproofs/cp1.png' width='400' height='600'/>
        <Image  className={styles.proofimg} src='/clientproofs/cp2.png' width='400' height='600'/>
        <Image  className={styles.proofimg} src='/clientproofs/cp3.png' width='550' height='600'/>

            </div>
           
            <div className={styles.num}>04</div>  
        <div className={styles.title4}> Design Mockups </div>

        <div className={styles.proofimgcont1}>

             <Image className={styles.proofimg} src='/can1.png' width='400' height='600'/>
        <Image  className={styles.proofimg} src='/can2.png' width='400' height='600'/>
        <Image  className={styles.proofimg} src='/can3.png' width='400' height='600'/>
        
            </div>
       
           
      </main>
    </>
  )
}
