import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router';
import Link from 'next/link';
import Nav from '@/components/nav';



const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image className={styles.logo} onClick={() => router.push('/')} src='/logo.png' width='200' height='100'/>
        <Nav/>
        <div className={styles.topcont}> 
        <div className={styles.titlecont}> 
 <Link href='/about' className={styles.title1}>Hey there, I'm Soleil</Link> 
        <div className={styles.title2}>Let's Connect!</div> 
        </div>

        </div>
      <div className={styles.connectdesc}> currently seeking an opportunity in Digital Design, UX/UI Design, and Graphic Design</div>
      
      <div className={styles.socialcont}> 
        <div className={styles.line1}></div>
        <div className={styles.socialcont1}> 

<Link  className={styles.social} href="mailto:sndagneau@gmail.com"> Email </Link>
      <Image className={styles.arrow1} src='/arrow-right.svg' width='50' height='50'/>
        </div>
 <div className={styles.line1}></div>
        <div className={styles.socialcont1}> 
        

 <Link className={styles.social} href='https://www.linkedin.com/in/soleildagneau' target="_blank" rel="noopener noreferrer"> LinkedIn </Link>
      <Image className={styles.arrow1} src='/arrow-right.svg' width='50' height='50'/>
        </div>
 <div className={styles.line1}></div>
        <div className={styles.socialcont1}> 
<Link className={styles.social} href='https://www.instagram.com/notsoleil/' target="_blank" rel="noopener noreferrer"> Instagram </Link>
      <Image className={styles.arrow1} src='/arrow-right.svg' width='50' height='50'/>
        </div>
      
     
     
     
      
      </div>

   
      
      </main>
    </>
  )
}
