import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router';
import Link from 'next/link';
import Nav from '@/components/nav';



const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image className={styles.logo} onClick={() => router.push('/')} src='/logo.png' width='200' height='100'/>
        <Nav/>
        <div className={styles.topcont}> 
        <div className={styles.titlecont}> 
 <Link href='/about' className={styles.title1}>Hello, I'm Soleil</Link> 
        <div className={styles.title2}>a UX/UI Designer</div> 
        </div>
         
        <Image className={styles.headshot} src='/headshot.png' width='180' height='180'/>
        
        </div>
        <div className={styles.line}></div>

      <div className={styles.projectcont}> 
      <div>
        <div className={styles.projecttitle} 
        onClick={() => router.push('/ohana')}> OHANA</div>
        <div className={styles.projectdesc}> An accessible errand app</div>
        <div className={styles.projectkey}> UX/UI Design</div>
        <div className={styles.projectkey}> Graphic Design</div>
        <div className={styles.projectkey}> Front-end Web Development</div>
        <div className={styles.projectkey}> Project Management</div>
        <div className={styles.projectkey}> Product Design</div>
        <div className={styles.projectkey}> Mobile Design</div>
        <div className={styles.projectkey}> Visual Design</div>
        </div>
        <Image className={styles.picture} 
         onClick={() => router.push('/ohana')}
        src='/ohanatutorial.jpg' width='400' height='500'/>
        
        <Image className={styles.arrow} 
         onClick={() => router.push('/ohana')}
        src='/arrow-right.svg' width='100' height='100'/>

      </div>
      <div className={styles.line}></div>
      <div className={styles.projectcont}> 
      <div className={styles.projectitems}> 

        <div className={styles.projecttitle} onClick={() => router.push('/localscoop')}> LocalScoop</div>
        <div className={styles.projectdesc1}> A marketplace app for small businesses</div>
        <div className={styles.projectkey}> UX/UI Design</div>
        <div className={styles.projectkey}> Graphic Design</div>
        <div className={styles.projectkey}> Product Design</div>
        <div className={styles.projectkey}> Mobile Design</div>
        <div className={styles.projectkey}> Visual Design</div>
      </div>
      <Image className={styles.picture} onClick={() => router.push('/localscoop')} src='/localscoop.jpg' width='600' height='450'/>
        
        <Image className={styles.arrow} onClick={() => router.push('/localscoop')} src='/arrow-right.svg' width='100' height='100'/>

      </div>
      <div className={styles.line}></div>
      <div className={styles.projectcont}> 
      <div>
        <div className={styles.projecttitle}> Beach House Brewing</div>
        <div className={styles.projectdesc1}> Craft brewery can designs</div>
        <div className={styles.projectkey}> UX/UI Design</div>
        <div className={styles.projectkey}> Graphic Design</div>
        <div className={styles.projectkey}> Visual Design</div>
        </div>
        <Image className={styles.picture} src='/cans.png' width='600' height='400'/>
        
        <Image className={styles.arrow} src='/arrow-right.svg' width='100' height='100'/>

      </div>
      <div className={styles.line}></div>
      <div className={styles.projectcont}> 
      <div>
<div className={styles.projecttitle}> The 70's in Retrospect</div>
        <div className={styles.projectdesc}> Magazine</div>
        <div className={styles.projectkey}> UX/UI Design</div>
        <div className={styles.projectkey}> Graphic Design</div>
        <div className={styles.projectkey}> Visual Design</div>
        </div>
        <Image className={styles.picture} src='/magazine.png' width='600' height='500'/>

        <Image className={styles.arrow} src='/arrow-right.svg' width='100' height='100'/>

      </div>
      <div className={styles.line}></div>

      <div className={styles.connect}> Let's connect</div>
      <div className={styles.connectdesc}> currently seeking an opportunity in Digital Design, UX/UI Design, and Graphic Design</div>
      
      <div className={styles.socialcont}> 
        <div className={styles.line1}></div>
        <div className={styles.socialcont1}> 

<Link  className={styles.social} href="mailto:sndagneau@gmail.com"> Email </Link>
      <Image className={styles.arrow1} src='/arrow-right.svg' width='50' height='50'/>
        </div>
 <div className={styles.line1}></div>
        <div className={styles.socialcont1}> 
        

 <Link className={styles.social} href='https://www.linkedin.com/in/soleildagneau' target="_blank" rel="noopener noreferrer"> LinkedIn </Link>
      <Image className={styles.arrow1} src='/arrow-right.svg' width='50' height='50'/>
        </div>
 <div className={styles.line1}></div>
        <div className={styles.socialcont1}> 
<Link className={styles.social} href='https://www.instagram.com/notsoleil/' target="_blank" rel="noopener noreferrer"> Instagram </Link>
      <Image className={styles.arrow1} src='/arrow-right.svg' width='50' height='50'/>
        </div>
      
     
     
     
      
      </div>

   
      
      </main>
    </>
  )
}
