import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Nav from '@/components/nav'
import { useRouter } from 'next/router';


export default function Home() {
    const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image className={styles.logo} onClick={() => router.push('/')} src='/logo.png' width='200' height='100'/>
        <Nav/>

        <div className={styles.titlecont1}>
            <div className={styles.projecttitle}> The 70's in Retrospect</div>
        <div className={styles.projectlongdesc}> The magazine is about interior design, architecture and retrofuturism in the 1970's. It is designed with Adobe InDesign. </div>
       
        </div>
         <div className={styles.line}></div>
            <div className={styles.infocont}>
            <div className={styles.itemcont}> 
                    <div> Year </div>  <div className={styles.info1}> 2022 </div>
                </div>
                
                <div className={styles.itemcont}> 
                    <div> Tools </div>  <div className={styles.info}> InDesign </div>
                </div>
                <div className={styles.itemcont}> 
                    <div> Project Types </div>  <div className={styles.info}> Visual Design, Print, Magazine Design, UX/UI Design, Graphic Design </div>
                </div>
                <div className={styles.itemcont}> 
                    <div> Roles </div>  <div className={styles.info}> Graphic/Digital Designer </div>
                </div>
            </div>
        <Image className={styles.mainpicture} src='/magazine.png' width='1200' height='1000'/>

        <button className={styles.magbutton} onClick={() => router.push('https://indd.adobe.com/view/c6f2da0b-341f-4fc5-ab48-8f45bf9727d9')}> VIEW THE FULL MAGAZINE </button>
       

      </main>
    </>
  )
}
