import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'




const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image className={styles.logo} src='/logo.png' width='200' height='100'/>

        <div className={styles.titlecont1}>
            <div className={styles.projecttitle}> OHANA</div>
        <div className={styles.projectlongdesc}>  Ohana is an errand app made for people with accessibility issues. It aids this group with completing their tasks easier and more efficiently through the help of people they trust.</div>
       
        </div>
         <div className={styles.line}></div>
            <div className={styles.infocont}>
            <div className={styles.itemcont}> 
                    <div> Year </div>  <div className={styles.info1}> 2022 </div>
                </div>
                
                <div className={styles.itemcont}> 
                    <div> Tools </div>  <div className={styles.info}> Figma, Photoshop, InDesign, Illustrator </div>
                </div>
                <div className={styles.itemcont}> 
                    <div> Project Types </div>  <div className={styles.info}> Product Design, Mobile Design, Visual Design, Development (Front-end) </div>
                </div>
                <div className={styles.itemcont}> 
                    <div> Roles </div>  <div className={styles.info}> Project Manager, UX/UI Designer, Graphic Designer, Front-end Developer </div>
                </div>
            </div>
        <Image className={styles.picture} src='/ohanatutorial.jpg' width='800' height='900'/>
        <div className={styles.num}>01</div>
        <div className={styles.title3}> The Problem</div>
        
        <div className={styles.desc1}> Almost 1 in 4 Canadians reported having a physical disability or mobility challenges. Through more user research, we found that people with accessibility issues feel an overwhelming amount of guilt asking for help. Primary caregivers, such as spouses or parents, also reported feeling burnt out – but too guilty to express this.</div>

        
        <div className={styles.num3}>02</div>  
        <div className={styles.title4}> The Solution </div>

     
      
        <div className={styles.desc1}> 
        Ohana aims to reduce caregiver burnout 
        and the guilt that those with mobility issues 
        feel by providing an encouraging platform to connect those 
        in need with those who are looking to help.
        <br></br>
        <div className={styles.infotitle}> TRUST </div>
        <br></br>
        <div className={styles.info2}>
                    Those in need can invite members of their family, friends, neighbours or anyone they trust to the app. It is in their control.
         </div>
         <br></br>
        <div className={styles.infotitle}> COMMUNITY</div>
        <br></br>
        <div className={styles.info2}>
        A sense of community is created through both sides of the app – those in need and those who are willing to help.
         </div>
         <br></br>
        <div className={styles.infotitle}> MUTUAL BENEFIT</div>
        <br></br>
        <div className={styles.info2}>
        Reduces guilt of user in need and caregivers feel less burnt out without being solely relied on
         </div>


        </div>



            <div className={styles.num1}>03</div>  
        <div className={styles.title4}> The Design </div>

        <div className={styles.desc1}> 
        Before designing high-fidelity prototypes, we built a styleguide to ensure that multiple designers are able to design the app in a clear and united way. It helped mirror the corporate style and ensures consistency with everything from design to writing.
        </div>

        <div className={styles.colortitle}> COLORS</div>

        <div className={styles.colorcont}>  
 <div className={styles.color1}>#126B8A</div>
 <div className={styles.color2}>#00ADC3</div>
 <div className={styles.color3}>#EDC81B</div>
 <div className={styles.color4}>#DC2228</div>
 <div className={styles.color5}>#4FCD92</div>
        </div>

        <div className={styles.colortitle1}> NEUTRALS</div>
        <div className={styles.colorcont}>  
 <div className={styles.color6}>#0A0908</div>
 <div className={styles.color7}>#2D2D2A</div>
 <div className={styles.color8}>#B5B5B5</div>
 <div className={styles.color9}>#E1E1E1</div>
 <div className={styles.color10}>#F7F5F3</div>
        </div>
       
       
        <div className={styles.colortitle1}> TYPOGRAPHY</div>
        <Image className={styles.fontimg} src='/fonts.png' width='500' height='500' />

        <div className={styles.colortitle1}> INTERACTIVE ELEMENTS</div>
        <div className={styles.colortitle1}> BUTTONS</div>
        <Image className={styles.fontimg} src='/buttons.png' width='550' height='300' />

        <div className={styles.colortitle1}> TABS</div>
        <Image className={styles.fontimg} src='/tabactive.png' width='300' height='200' />
       
        
        <div className={styles.colortitle1}> TOOLTIPS</div>
        <Image className={styles.fontimg} src='/tooltip.png' width='300' height='220' />

        <div className={styles.num}>04</div>  
        <div className={styles.title4}> Final Design </div>
        <div className={styles.colortitle1}> HIGH FIDELITY PROTOTYPE</div>
        <div className={styles.desc1}> With the result of the user testing and the style guide, 
            we built our high-fidelity prototypes and made sure the overall 
            user experience is intuitive. The final prototype shows a complete 
            idea of ​​how the Reshare app will look like in the final result.</div>

<div  className={styles.vidcont} >
     <video className={styles.vid} src="/ohanavid.mp4" controls width={640} height={360} />

      
    </div>
           
      </main>
    </>
  )
}
